### ISSUE TITLE
Support *zap.SugaredLogger on zap instrumentation

### ISSUE THREAD

**Issue by pragmaticivan** [uptrace/uptrace-go#103]
It appears the current instrumentation does not support Suggared Logger interface. It also does not return the actual Zap Interface and creates conflict with app usage.

**Comment by pragmaticivan** [comment]
@vmihailenco the second part makes sense was just wondering if that could become a `quick drop in replacement` but having SuggaredLogger sounds great.

**Comment by vmihailenco** [comment]
Sugared API should be supported in v1.0.5 - see [otelzap](https://github.com/uptrace/uptrace-go/tree/master/extra/otelzap#sugared-logger)
