### ISSUE TITLE
rpc encoding error

### ISSUE THREAD

**Issue by schmurfy** [uptrace/uptrace-go#108]
I am getting weird log entries on one of our services, I think the message is printed by `uptrace-go` and although this is not an error in the library itself I am trying to find it to find what exactly is the problematic content xD

```
2021/10/21 10:43:46 rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8
```

Do you have any idea where this might originate from ?
I am sure the message is not from our service itself since we use zap to output json formatted log, no `log.Printxx` is used anywhere.

**Comment by vmihailenco** [comment]
:+1: Some options:
- use `strings.ToValidUTF8(s, "")` if that is really a string with some invalid UTF-8 chars
- hex encode the data
- use `json.Marshal` which will hex-encode it for you
