### ISSUE TITLE
How to export to an OpenTelemetry Collector?

### ISSUE THREAD

**Issue by matthyx** [uptrace/uptrace-go#140]
I have several Go microservices that are using uptrace-go for sending metrics and traces to uptrace.
Following https://uptrace.dev/opentelemetry/collector.html I would like to configure these services to send to a local OpenTelemetry Collector acting as a middle-man that will forward to uptrace as explained in https://uptrace.dev/opentelemetry/collector.html#exporting-data-to-uptrace

How should I set up my `UPTRACE_DSN` environment variable to do so?

Thanks for your support.

**Comment by vmihailenco** [comment]
Hello @matthyx,

Assuming you have Otel collector listening on `localhost:4317`, you can try `UPTRACE_DSN=http://localhost:14317` (replace http with https if you have TLS).

Let me know if that works and I will update the docs.

**Comment by matthyx** [comment]
Hi @vmihailenco thanks for the idea... I did try and got this error message:
`uptrace: 2023/01/20 13:01:24 uptrace.go:38: invalid Uptrace DSN: DSN="http://localhost:4317" does not have a project id (Uptrace is disabled)`

**Comment by vmihailenco** [comment]
I see. Please try `UPTRACE_DSN=http://token@localhost:4317/1` with the dummy project id.

**Comment by matthyx** [comment]
Yes, it definitely works for the spans, however not the metrics and I get such error messages:
`2023/01/20 13:13:13 rpc error: code = Unimplemented desc = unknown service opentelemetry.proto.collector.metrics.v1.MetricsService`

**Comment by vmihailenco** [comment]
I tried the [metrics](example/metrics) in this repo:

```shell
cd example/metrics
UPTRACE_DSN=http://localhost:4317 make
```

Seems to be working fine. How can I reproduce the issue?

**Comment by vmihailenco** [comment]
As a guess, you probably did not enable metrics pipeline in the Otel collector:

```yaml
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, resourcedetection]
      exporters: [otlp]
```

**Comment by matthyx** [comment]
Indeed it works, thanks a lot.

I did copy and paste the config from here: https://uptrace.dev/opentelemetry/collector.html#configuration
Maybe you could add the metrics part there?

**Comment by matthyx** [comment]
I think with good docs this issue can be closed.
Regards.

**Comment by vmihailenco** [comment]
That's an overlook, thanks! I will update the docs.
