### ISSUE TITLE
Enhancement: way to configure multiple metric readers+exporters

### ISSUE THREAD

**Issue by rattuscz** [uptrace/uptrace-go#145]
I was investigating options to have our apps instrumented to export some default metrics to central prometheus.
I already have setup uptrace for tracing so I wanted to keep option for sending those metrics to uptrace too.

Unfortunately because go OTEL MeterProvider is immutable after creation - you by design cannot add new readers (and thus exporters) even though the constructor supports multiple readers.

That means the best option would be to allow sending my own configured `metric.Reader` as config option for uptrace to use during creation of the MeterProvider.

Currently I have to choose if I want to send to uptrace OR expose classic http `/metrics` endpoint as i would have to overwrite the MeterProvider and lose uptrace client.

The option could look something like
```go
// WithMetricsReader provide custom reader for global MeterProvider to allow multiple readers/exporters
func WithMetricsReader(reader metric.Reader) MetricsOption {
	return metricsOption(func(conf *config) {
		conf.readers = append(conf.readers, reader)
	})
}
```

and during creation of MeterProvider:
```go
customReaders := make([]metric.Option, len(cfg.readers))
for i := range(cfg.readers) {
	customReaders[i] = metric.WithReader(cfg.readers[i])
}

provider := metric.NewMeterProvider(
	metric.WithReader(reader),
	metric.WithResource(cfg.newResource()),
	customReaders...
)
```

I think that's all needed to cleanly integrate our own custom readers + exporters inside uptrace.
Not sure if it's against overall design that all metrics should go through single channel to OTEL Collector/Uptrace

Any comments/suggestions welcome :-)

**Comment by vmihailenco** [comment]
That sounds good. Perhaps we should even go with a more general API like:

```go
func WithMetricOption(option metric.Option) MetricsOption {
	return metricsOption(func(conf *config) {
		conf.metricOptions = append(conf.metricOptions, option)
	})
}
```

Then you can use it like this:

```go
uptrace.ConfigureOpentelemetry(uptrace.WithMetricOption(
    metric.WithReader(promReader),
))
```

This way you can add/overwrite any existing `metric.Option` provided by Otel SDK. What do you think?

**Comment by rattuscz** [comment]
Sure sounds even better. Will be more future proof if any new options come around.
