### ISSUE TITLE
cannot set service name (service:unknown_service)

### ISSUE THREAD

**Issue by schmurfy** [uptrace/uptrace-go#62]
I was up and running fairly quickly with your library and service, thanks for this I really like it so far  :+1

I have an issue I cannot manage to solve though, My service is named `service:unknown_service`  and I have no idea where to set its name. So far I have this:

```go
upclient := uptrace.NewClient(&uptrace.Config{
		DSN: "...",
	})
```

I don't see any field which could hold the service name aside of maybe `Resource` but since this is a map i have no idea what to put in there.

**Comment by schmurfy** [comment]
I found it by this is far from obvious, here is what I needed to do:

```go
res := resource.NewWithAttributes(
  label.String("service.name", "test-app"),
)

upclient := uptrace.NewClient(&uptrace.Config{
  DSN:      "...",
  Resource: res,
})
```

**Comment by vmihailenco** [comment]
Thanks for the feedback. This was improved in v0.6.1:

```go
	upclient := uptrace.NewClient(&uptrace.Config{
		// copy your project DSN here or use UPTRACE_DSN env var
		DSN: "",

		ServiceName:    "test",
		ServiceVersion: "v1.0.0",
                ResourceAttributes: ...,
	})
```

With the config above uptrace-go also uses `host.*` [detector](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/resource#WithHost). If you wish to continue using the old method it should be to benefit from built-in detectors

```go
resource, err := resource.New(
    ctx,
    resource.WithAttributes(
        label.String(otelattr.ServiceName, Config.Service),
    ),
)
if err != nil {
    panic(err)
}

upclient := uptrace.NewClient(&uptrace.Config{
  DSN:      "...",
  Resource: res,
})
```
